# Generated by Django 5.1.7 on 2025-03-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
